service: cloud-ams-api

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: dev

resources:
  Resources:
    CloudAmsDB:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: title
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: title
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: CmsPage

functions:
  getPage:
    handler: handler.getPage
    events:
      - http:
          path: getPage
          method: get
          cors: true
  addPage:
    handler: handler.addPage
    events:
      - http:
          path: addPage
          method: post
          cors: true
  updatePage:
    handler: handler.updatePage
    events:
      - http:
          path: updatePage
          method: put
          cors: true
  meetings:
    handler: handler.meetings
    events:
      - http:
          path: meetings
          method: get
          cors: true


