service: cloud-ams-api

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: dev


functions:
  getPage:
    handler: handler.getPage
    events:
      - http:
          path: getPage
          method: get
          cors: true
  addPage:
    handler: handler.addPage
    events:
      - http:
          path: addPage
          method: post
          cors: true
  updatePage:
    handler: handler.updatePage
    events:
      - http:
          path: updatePage
          method: put
          cors: true


